[package]
name = "windowmanager"
version = "0.0.1"
authors = ["Sergei Shilovsky <sshilovsky@gmail.com>"]

[dependencies]
libc = "*"

[dependencies.xlib]
git = "https://github.com/servo/rust-xlib.git"

[[bin]]
name = "windowmanager"
