[package]
name = "windowmanager"
version = "0.0.1"
authors = ["Sergei Shilovsky <sshilovsky@gmail.com>"]

[dependencies.xlib]
git = "https://github.com/servo/rust-xlib.git"

[dependencies.xinerama]
git = "https://github.com/Kintaro/rust-xinerama.git"

[[bin]]
name = "windowmanager"
